module.exports = [
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'C3POCHEWBACCA',
      'C3POLEGENDARY',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
    ],
    seen: '172',
    winPerc: '100%',
    avgBanners: '57',
    opponentSquad: [
      'BOSSK',
      'BOBAFETT',
      'GREEFKARGA',
      'JANGOFETT',
      'THEMANDALORIAN',
    ],
  },
  {
    counterSquad: [
      'JEDIKNIGHTREVAN',
      'BASTILASHAN',
      'GRANDMASTERYODA',
      'JOLEEBINDO',
      'BLANK',
    ],
    seen: '70',
    winPerc: '100%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'ENFYSNEST', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'VEERS',
      'COLONELSTARCK',
      'DEATHTROOPER',
      'RANGETROOPER',
      'SNOWTROOPER',
    ],
    seen: '69',
    winPerc: '72.5%',
    avgBanners: '59',
    opponentSquad: [
      'BOSSK',
      'BOBAFETT',
      'GREEFKARGA',
      'JANGOFETT',
      'THEMANDALORIAN',
    ],
  },
  {
    counterSquad: [
      'GEONOSIANBROODALPHA',
      'GEONOSIANSOLDIER',
      'GEONOSIANSPY',
      'POGGLETHELESSER',
      'SUNFAC',
    ],
    seen: '51',
    winPerc: '100%',
    avgBanners: '58',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'GREEDO'],
  },
  {
    counterSquad: [
      'GEONOSIANBROODALPHA',
      'GEONOSIANSOLDIER',
      'GEONOSIANSPY',
      'POGGLETHELESSER',
      'SUNFAC',
    ],
    seen: '43',
    winPerc: '95.4%',
    avgBanners: '57',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'BLANK',
      'BLANK',
    ],
    seen: '42',
    winPerc: '97.6%',
    avgBanners: '61',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'JANGOFETT'],
  },
  {
    counterSquad: ['REYJEDITRAINING', 'BB8', 'FINN', 'R2D2_LEGENDARY', 'REY'],
    seen: '42',
    winPerc: '83.3%',
    avgBanners: '57',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'ENFYSNEST', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'C3POCHEWBACCA',
      'C3POLEGENDARY',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
    ],
    seen: '41',
    winPerc: '100%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEFKARGA', 'THEMANDALORIAN'],
  },
  {
    counterSquad: ['REYJEDITRAINING', 'BB8', 'FINN', 'RESISTANCETROOPER', 'REY'],
    seen: '40',
    winPerc: '100%',
    avgBanners: '58',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'GREEDO'],
  },
  {
    counterSquad: [
      'GEONOSIANBROODALPHA',
      'GEONOSIANSOLDIER',
      'GEONOSIANSPY',
      'POGGLETHELESSER',
      'SUNFAC',
    ],
    seen: '40',
    winPerc: '97.5%',
    avgBanners: '58',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'VEERS',
      'COLONELSTARCK',
      'DEATHTROOPER',
      'RANGETROOPER',
      'SNOWTROOPER',
    ],
    seen: '38',
    winPerc: '94.7%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'GREEDO'],
  },
  {
    counterSquad: [
      'MOTHERTALZIN',
      'ASAJVENTRESS',
      'DAKA',
      'NIGHTSISTERSPIRIT',
      'NIGHTSISTERZOMBIE',
    ],
    seen: '35',
    winPerc: '82.9%',
    avgBanners: '54',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'GREEDO'],
  },
  {
    counterSquad: [
      'VEERS',
      'COLONELSTARCK',
      'DEATHTROOPER',
      'RANGETROOPER',
      'SNOWTROOPER',
    ],
    seen: '33',
    winPerc: '84.9%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEFKARGA', 'THEMANDALORIAN'],
  },
  {
    counterSquad: [
      'REYJEDITRAINING',
      'BB8',
      'R2D2_LEGENDARY',
      'RESISTANCETROOPER',
      'REY',
    ],
    seen: '33',
    winPerc: '97.0%',
    avgBanners: '58',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'GREEDO'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'C3POCHEWBACCA',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'BLANK',
    ],
    seen: '31',
    winPerc: '100%',
    avgBanners: '60',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEFKARGA', 'THEMANDALORIAN'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'BLANK',
      'BLANK',
    ],
    seen: '31',
    winPerc: '100%',
    avgBanners: '61',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'ZAMWESELL'],
  },
  {
    counterSquad: ['REYJEDITRAINING', 'BB8', 'FINN', 'RESISTANCETROOPER', 'REY'],
    seen: '30',
    winPerc: '93.3%',
    avgBanners: '57',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'JANGOFETT'],
  },
  {
    counterSquad: ['DARTHREVAN', 'BASTILASHANDARK', 'DARTHMALAK', 'HK47', 'BLANK'],
    seen: '30',
    winPerc: '100%',
    avgBanners: '58',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'ENFYSNEST', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'BLANK',
      'BLANK',
    ],
    seen: '29',
    winPerc: '100%',
    avgBanners: '61',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'GREEDO'],
  },
  {
    counterSquad: [
      'VEERS',
      'COLONELSTARCK',
      'DEATHTROOPER',
      'RANGETROOPER',
      'SNOWTROOPER',
    ],
    seen: '29',
    winPerc: '79.3%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'VEERS',
      'COLONELSTARCK',
      'DEATHTROOPER',
      'RANGETROOPER',
      'SNOWTROOPER',
    ],
    seen: '28',
    winPerc: '92.9%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'JANGOFETT', 'ZAMWESELL'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'BLANK',
      'BLANK',
    ],
    seen: '28',
    winPerc: '100%',
    avgBanners: '60',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'BLANK',
      'BLANK',
    ],
    seen: '27',
    winPerc: '96.3%',
    avgBanners: '60',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'JANGOFETT', 'ZAMWESELL'],
  },
  {
    counterSquad: [
      'REYJEDITRAINING',
      'BB8',
      'FINN',
      'R2D2_LEGENDARY',
      'RESISTANCETROOPER',
    ],
    seen: '27',
    winPerc: '100%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'GREEDO'],
  },
  {
    counterSquad: [
      'GEONOSIANBROODALPHA',
      'GEONOSIANSOLDIER',
      'GEONOSIANSPY',
      'POGGLETHELESSER',
      'SUNFAC',
    ],
    seen: '26',
    winPerc: '80.8%',
    avgBanners: '57',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEFKARGA', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'VEERS',
      'COLONELSTARCK',
      'DEATHTROOPER',
      'RANGETROOPER',
      'SNOWTROOPER',
    ],
    seen: '26',
    winPerc: '92.3%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'IG88'],
  },
  {
    counterSquad: [
      'DARTHTRAYA',
      'DARTHNIHILUS',
      'DARTHSION',
      'EMPERORPALPATINE',
      'VADER',
    ],
    seen: '26',
    winPerc: '92.3%',
    avgBanners: '55',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'ENFYSNEST', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'C3POLEGENDARY',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'BLANK',
    ],
    seen: '25',
    winPerc: '100%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'JANGOFETT'],
  },
  {
    counterSquad: ['REYJEDITRAINING', 'BB8', 'FINN', 'RESISTANCETROOPER', 'REY'],
    seen: '25',
    winPerc: '96%',
    avgBanners: '56',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'BLANK',
      'BLANK',
    ],
    seen: '24',
    winPerc: '100%',
    avgBanners: '61',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'IG88'],
  },
  {
    counterSquad: [
      'REYJEDITRAINING',
      'BB8',
      'R2D2_LEGENDARY',
      'RESISTANCETROOPER',
      'REY',
    ],
    seen: '24',
    winPerc: '100%',
    avgBanners: '58',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'IG88'],
  },
  {
    counterSquad: [
      'GEONOSIANBROODALPHA',
      'GEONOSIANSOLDIER',
      'GEONOSIANSPY',
      'POGGLETHELESSER',
      'SUNFAC',
    ],
    seen: '23',
    winPerc: '95.7%',
    avgBanners: '56',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'ZAMWESELL'],
  },
  {
    counterSquad: ['REYJEDITRAINING', 'BB8', 'FINN', 'RESISTANCETROOPER', 'REY'],
    seen: '23',
    winPerc: '69.6%',
    avgBanners: '56',
    opponentSquad: [
      'BOSSK',
      'BOBAFETT',
      'GREEFKARGA',
      'JANGOFETT',
      'THEMANDALORIAN',
    ],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'C3POLEGENDARY',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'BLANK',
    ],
    seen: '23',
    winPerc: '100%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'ZAMWESELL'],
  },
  {
    counterSquad: [
      'MOTHERTALZIN',
      'ASAJVENTRESS',
      'DAKA',
      'NIGHTSISTERSPIRIT',
      'NIGHTSISTERZOMBIE',
    ],
    seen: '23',
    winPerc: '69.6%',
    avgBanners: '55',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEFKARGA', 'THEMANDALORIAN'],
  },
  {
    counterSquad: [
      'REYJEDITRAINING',
      'BB8',
      'FINN',
      'R2D2_LEGENDARY',
      'RESISTANCETROOPER',
    ],
    seen: '22',
    winPerc: '100%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'JANGOFETT'],
  },
  {
    counterSquad: ['REYJEDITRAINING', 'BB8', 'FINN', 'RESISTANCETROOPER', 'REY'],
    seen: '22',
    winPerc: '86.4%',
    avgBanners: '55',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'JANGOFETT', 'ZAMWESELL'],
  },
  {
    counterSquad: ['REYJEDITRAINING', 'BB8', 'FINN', 'RESISTANCETROOPER', 'REY'],
    seen: '22',
    winPerc: '100%',
    avgBanners: '58',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'ZAMWESELL'],
  },
  {
    counterSquad: ['REYJEDITRAINING', 'BB8', 'FINN', 'RESISTANCETROOPER', 'REY'],
    seen: '22',
    winPerc: '90.9%',
    avgBanners: '57',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEFKARGA', 'THEMANDALORIAN'],
  },
  {
    counterSquad: [
      'VEERS',
      'COLONELSTARCK',
      'DEATHTROOPER',
      'RANGETROOPER',
      'SNOWTROOPER',
    ],
    seen: '21',
    winPerc: '71.4%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'ZAMWESELL'],
  },
  {
    counterSquad: [
      'JEDIKNIGHTREVAN',
      'BASTILASHAN',
      'GRANDMASTERYODA',
      'HERMITYODA',
      'JOLEEBINDO',
    ],
    seen: '21',
    winPerc: '100%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEFKARGA', 'THEMANDALORIAN'],
  },
  {
    counterSquad: [
      'DARTHREVAN',
      'BASTILASHANDARK',
      'HK47',
      'SITHMARAUDER',
      'SITHTROOPER',
    ],
    seen: '20',
    winPerc: '100%',
    avgBanners: '57',
    opponentSquad: [
      'BOSSK',
      'BOBAFETT',
      'GREEFKARGA',
      'JANGOFETT',
      'THEMANDALORIAN',
    ],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'C3POLEGENDARY',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'BLANK',
    ],
    seen: '20',
    winPerc: '100%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'JANGOFETT', 'ZAMWESELL'],
  },
  {
    counterSquad: [
      'VEERS',
      'COLONELSTARCK',
      'DEATHTROOPER',
      'RANGETROOPER',
      'SNOWTROOPER',
    ],
    seen: '19',
    winPerc: '84.2%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEFKARGA', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'ASAJVENTRESS',
      'DAKA',
      'MOTHERTALZIN',
      'NIGHTSISTERSPIRIT',
      'NIGHTSISTERZOMBIE',
    ],
    seen: '19',
    winPerc: '100%',
    avgBanners: '54',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'IG88'],
  },
  {
    counterSquad: [
      'VEERS',
      'ADMIRALPIETT',
      'COLONELSTARCK',
      'DEATHTROOPER',
      'RANGETROOPER',
    ],
    seen: '19',
    winPerc: '94.7%',
    avgBanners: '60',
    opponentSquad: [
      'BOSSK',
      'BOBAFETT',
      'GREEFKARGA',
      'JANGOFETT',
      'THEMANDALORIAN',
    ],
  },
  {
    counterSquad: [
      'JEDIKNIGHTREVAN',
      'BASTILASHAN',
      'HERMITYODA',
      'JEDIKNIGHTLUKE',
      'OLDBENKENOBI',
    ],
    seen: '19',
    winPerc: '100%',
    avgBanners: '59',
    opponentSquad: [
      'BOSSK',
      'BOBAFETT',
      'GREEFKARGA',
      'JANGOFETT',
      'THEMANDALORIAN',
    ],
  },
  {
    counterSquad: [
      'ASAJVENTRESS',
      'DAKA',
      'MOTHERTALZIN',
      'NIGHTSISTERSPIRIT',
      'NIGHTSISTERZOMBIE',
    ],
    seen: '19',
    winPerc: '84.2%',
    avgBanners: '53',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'JANGOFETT', 'THEMANDALORIAN'],
  },
  {
    counterSquad: [
      'GRIEVOUS',
      'B1BATTLEDROIDV2',
      'B2SUPERBATTLEDROID',
      'COUNTDOOKU',
      'DROIDEKA',
    ],
    seen: '19',
    winPerc: '89.5%',
    avgBanners: '56',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'VEERS',
      'COLONELSTARCK',
      'DEATHTROOPER',
      'RANGETROOPER',
      'SNOWTROOPER',
    ],
    seen: '19',
    winPerc: '94.7%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'GEONOSIANBROODALPHA',
      'GEONOSIANSOLDIER',
      'GEONOSIANSPY',
      'POGGLETHELESSER',
      'SUNFAC',
    ],
    seen: '19',
    winPerc: '100%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'IG88'],
  },
  {
    counterSquad: [
      'REYJEDITRAINING',
      'BB8',
      'R2D2_LEGENDARY',
      'RESISTANCETROOPER',
      'REY',
    ],
    seen: '18',
    winPerc: '94.4%',
    avgBanners: '57',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'R2D2_LEGENDARY',
      'BLANK',
    ],
    seen: '18',
    winPerc: '100%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'C3POLEGENDARY',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'BLANK',
    ],
    seen: '18',
    winPerc: '94.4%',
    avgBanners: '60',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'GREEDO'],
  },
  {
    counterSquad: [
      'JEDIKNIGHTREVAN',
      'GRANDMASTERYODA',
      'HERMITYODA',
      'JOLEEBINDO',
      'BLANK',
    ],
    seen: '17',
    winPerc: '100%',
    avgBanners: '60',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'ENFYSNEST', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'R2D2_LEGENDARY',
      'BLANK',
    ],
    seen: '17',
    winPerc: '100%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'JANGOFETT', 'ZAMWESELL'],
  },
  {
    counterSquad: [
      'REYJEDITRAINING',
      'BB8',
      'R2D2_LEGENDARY',
      'RESISTANCETROOPER',
      'REY',
    ],
    seen: '17',
    winPerc: '100%',
    avgBanners: '58',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'IG88'],
  },
  {
    counterSquad: [
      'ASAJVENTRESS',
      'DAKA',
      'MOTHERTALZIN',
      'NIGHTSISTERSPIRIT',
      'NIGHTSISTERZOMBIE',
    ],
    seen: '17',
    winPerc: '47.1%',
    avgBanners: '53',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEFKARGA', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'C3POLEGENDARY',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'R2D2_LEGENDARY',
    ],
    seen: '17',
    winPerc: '100%',
    avgBanners: '58',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'JANGOFETT', 'ZAMWESELL'],
  },
  {
    counterSquad: [
      'MOTHERTALZIN',
      'ASAJVENTRESS',
      'DAKA',
      'NIGHTSISTERSPIRIT',
      'NIGHTSISTERZOMBIE',
    ],
    seen: '17',
    winPerc: '88.2%',
    avgBanners: '54',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'ZAMWESELL'],
  },
  {
    counterSquad: ['REYJEDITRAINING', 'BB8', 'FINN', 'RESISTANCETROOPER', 'REY'],
    seen: '17',
    winPerc: '94.1%',
    avgBanners: '58',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'IG88'],
  },
  {
    counterSquad: ['REYJEDITRAINING', 'BB8', 'FINN', 'RESISTANCETROOPER', 'REY'],
    seen: '17',
    winPerc: '100%',
    avgBanners: '58',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'GREEDO', 'IG88'],
  },
  {
    counterSquad: [
      'GEONOSIANBROODALPHA',
      'GEONOSIANSOLDIER',
      'GEONOSIANSPY',
      'POGGLETHELESSER',
      'SUNFAC',
    ],
    seen: '17',
    winPerc: '100%',
    avgBanners: '57',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'ZAMWESELL'],
  },
  {
    counterSquad: [
      'GRIEVOUS',
      'B1BATTLEDROIDV2',
      'B2SUPERBATTLEDROID',
      'COUNTDOOKU',
      'DROIDEKA',
    ],
    seen: '16',
    winPerc: '100%',
    avgBanners: '56',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'GEONOSIANBROODALPHA',
      'GEONOSIANSOLDIER',
      'GEONOSIANSPY',
      'POGGLETHELESSER',
      'SUNFAC',
    ],
    seen: '16',
    winPerc: '93.8%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'EMBO'],
  },
  {
    counterSquad: [
      'GEONOSIANBROODALPHA',
      'GEONOSIANSOLDIER',
      'GEONOSIANSPY',
      'POGGLETHELESSER',
      'SUNFAC',
    ],
    seen: '16',
    winPerc: '62.5%',
    avgBanners: '54',
    opponentSquad: [
      'BOSSK',
      'ENFYSNEST',
      'GREEFKARGA',
      'JANGOFETT',
      'THEMANDALORIAN',
    ],
  },
  {
    counterSquad: [
      'ASAJVENTRESS',
      'DAKA',
      'MOTHERTALZIN',
      'NIGHTSISTERSPIRIT',
      'NIGHTSISTERZOMBIE',
    ],
    seen: '16',
    winPerc: '81.3%',
    avgBanners: '53',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'REYJEDITRAINING',
      'BB8',
      'R2D2_LEGENDARY',
      'RESISTANCETROOPER',
      'REY',
    ],
    seen: '16',
    winPerc: '100%',
    avgBanners: '57',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEFKARGA', 'THEMANDALORIAN'],
  },
  {
    counterSquad: [
      'JEDIKNIGHTREVAN',
      'BASTILASHAN',
      'GRANDMASTERYODA',
      'HERMITYODA',
      'JOLEEBINDO',
    ],
    seen: '16',
    winPerc: '100%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'JANGOFETT', 'ZAMWESELL'],
  },
  {
    counterSquad: [
      'REYJEDITRAINING',
      'BB8',
      'C3POLEGENDARY',
      'R2D2_LEGENDARY',
      'REY',
    ],
    seen: '16',
    winPerc: '100%',
    avgBanners: '56',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'ENFYSNEST', 'JANGOFETT'],
  },
  {
    counterSquad: ['REYJEDITRAINING', 'BB8', 'FINN', 'RESISTANCETROOPER', 'REY'],
    seen: '16',
    winPerc: '93.8%',
    avgBanners: '57',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'IG88'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'C3POLEGENDARY',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'BLANK',
    ],
    seen: '16',
    winPerc: '100%',
    avgBanners: '60',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEFKARGA', 'THEMANDALORIAN'],
  },
  {
    counterSquad: [
      'VEERS',
      'COLONELSTARCK',
      'DEATHTROOPER',
      'RANGETROOPER',
      'SNOWTROOPER',
    ],
    seen: '16',
    winPerc: '87.5%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'ZAMWESELL'],
  },
  {
    counterSquad: [
      'MOTHERTALZIN',
      'ASAJVENTRESS',
      'DAKA',
      'NIGHTSISTERSPIRIT',
      'NIGHTSISTERZOMBIE',
    ],
    seen: '16',
    winPerc: '93.8%',
    avgBanners: '54',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'ZAMWESELL'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'R2D2_LEGENDARY',
      'BLANK',
    ],
    seen: '16',
    winPerc: '100%',
    avgBanners: '60',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'GREEDO'],
  },
  {
    counterSquad: [
      'PADMEAMIDALA',
      'AHSOKATANO',
      'ANAKINKNIGHT',
      'GENERALKENOBI',
      'BLANK',
    ],
    seen: '15',
    winPerc: '100%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'ZAMWESELL'],
  },
  {
    counterSquad: ['REYJEDITRAINING', 'BB8', 'FINN', 'R2D2_LEGENDARY', 'REY'],
    seen: '15',
    winPerc: '100%',
    avgBanners: '57',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'ZAMWESELL'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'BLANK',
      'BLANK',
    ],
    seen: '15',
    winPerc: '93.3%',
    avgBanners: '61',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'CADBANE', 'DENGAR', 'EMBO'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'R2D2_LEGENDARY',
      'BLANK',
    ],
    seen: '15',
    winPerc: '100%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'MOTHERTALZIN',
      'ASAJVENTRESS',
      'DAKA',
      'NIGHTSISTERSPIRIT',
      'NIGHTSISTERZOMBIE',
    ],
    seen: '15',
    winPerc: '73.3%',
    avgBanners: '53',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'EMBO', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'C3POCHEWBACCA',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'BLANK',
    ],
    seen: '15',
    winPerc: '100%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'JANGOFETT', 'THEMANDALORIAN'],
  },
  {
    counterSquad: [
      'REYJEDITRAINING',
      'BB8',
      'EPIXFINN',
      'EPIXPOE',
      'R2D2_LEGENDARY',
    ],
    seen: '15',
    winPerc: '100%',
    avgBanners: '58',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'ENFYSNEST', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'OLDBENKENOBI',
      'BLANK',
    ],
    seen: '15',
    winPerc: '100%',
    avgBanners: '59',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEDO', 'JANGOFETT'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'C3POLEGENDARY',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'R2D2_LEGENDARY',
    ],
    seen: '15',
    winPerc: '80%',
    avgBanners: '58',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEFKARGA', 'THEMANDALORIAN'],
  },
  {
    counterSquad: [
      'COMMANDERLUKESKYWALKER',
      'CHEWBACCALEGENDARY',
      'HANSOLO',
      'BLANK',
      'BLANK',
    ],
    seen: '15',
    winPerc: '93.3%',
    avgBanners: '61',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEFKARGA', 'THEMANDALORIAN'],
  },
  {
    counterSquad: ['REYJEDITRAINING', 'BB8', 'FINN', 'R2D2_LEGENDARY', 'REY'],
    seen: '15',
    winPerc: '93.3%',
    avgBanners: '58',
    opponentSquad: ['BOSSK', 'BOBAFETT', 'DENGAR', 'GREEFKARGA', 'JANGOFETT'],
  },
];
